- name: configure mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql server
    ansible.builtin.package:
      name: mysql-server
      state: installed

# output:
# PLAY [configure mysql server] *********************************************************************************

# TASK [Gathering Facts] ****************************************************************************************
# ok: [172.31.90.161]

# TASK [install mysql server] ***********************************************************************************
# changed: [172.31.90.161]

# PLAY RECAP ****************************************************************************************************
# 172.31.90.161              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
